### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [satuso/forum-app#1]
# Full Stack projektin katselmointi

Terve @satuso! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein?

- Rekisteröin uuden käyttäjän ja kirjauduin sisään
- Selasin ketjuja eri kategorioissa
- Lisäsin vastauksia ketjuihin
- Lisäsin uuden ketjun ja sinne vastauksia
- Selasin käyttäjiä
- Muokkasin käyttäjätietojani
- Kirjauduin ulos 

### Kokemus

- Foorumi-sovelluksen käyttöliittymä on tyylikäs ja kaikin puolin helppokäyttöinen, hyvää työtä! 💎
- Lomakkeissa on kattavat validoinnit
- Automaattinen sisäänkirjautuminen rekisteröitymisen jälkeen olisi kätevä toiminallisuus
- Etusivulla https://satuso-forum-frontend.herokuapp.com/ voisi olla käyttäjälle jotain hyödyllisempää sisältöä, esim. aktiivisimmat keskustelut

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- API-kutsut on abstrahoitu hyvin uudellenkäytettäviksi palveluiksi services-hakemistoon, hienoa!
- [Tokenin asettamiseen](https://github.com/satuso/forum-app/blob/main/forum-frontend/src/services/users.js#L5) liittyvää koodia on monessa services-hakemiston tiedostossa. Ehkä tämän logiikan voisi eriyttää omaan _token.js_-tiedostoon, jota muut tiedostot käyttävät?
- Fontteja voi myös ladata helposti [Google Fontsin](https://fonts.google.com/) kautta, niin fontti-tiedostoja ei tarvitse ylläpitää
- Redux Toolkittiä on hyödynnetty järkevästi
- API-kutsuihin liittyvää dataa ei välttämättä tarvitse ylläpitää Reduxin storessa. Esimerkiksi [React Query](https://react-query.tanstack.com/) -kirjaston avulla API-kutsut voi helposti abstrahoida yksinkertaisiksi, uudelleenkäytettäväksii hookeiksi
- Tyylejä kannattaa eritellä niitä käyttävien komponenttien mukaan omiksi kansiomoduuleikseen, esim. tähän tapaan:

  ```
  ThreadList/
    - index.jsx <- Komponentin koodi
    - style.css <- Komponentin käyttämät tyylit
  ```

  Tyylien luokkien nimissä voi käyttää komponentin nimeä etuliitteenä, esim. `.ThreadList__list` ja `.ThreadList__username`. Tämä vähentää riskiä luokkien nimien yhteentörmäyksessä. Modernimpi ratkaisu tähän ongelmaan on [css-moduulit](https://github.com/css-modules/css-modules) tai jokin CSS-in-JS-kirjasto, kuten [styled components](https://styled-components.com/)

- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- `res.json`- ja `res.send`-kutsujen yhteydessä `toJSON`-metodia ei tarvitse [erikseen kutsua](https://github.com/satuso/forum-app/blob/main/forum-backend/controllers/posts.js#L35). Kun JSON-muotoinen vastaus muodostetaan, `JSON.stringify`-metodi kutsuu sitä automaattisesti
- Reittien käsittelijöiden ainaisista `try { ... } catch (e) { console.log(e) }`-lohkoista pääsee helposti eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjaston avulla
- Tarkistetaanko [postauksen poistossa](https://github.com/satuso/forum-app/blob/main/forum-backend/controllers/posts.js#L78) ja [päivityksessä](https://github.com/satuso/forum-app/blob/main/forum-backend/controllers/posts.js#L87) autentikoituneen käyttäjän tietoja? Ilmeisesti tällä hetkellä kuka tahansa voi poistaa ja muokata postausta, jos tietää sen id:n?

## Kokonaisuus

Foorumi-sovelluksesta löytyy kaikki tarvittava toiminnallisuus käyttäjien välisille keskusteluille. Sen käyttöliittymä on näyttävä ja käyttäjäystävällinen. Katselmoinnin aikana ei ilmennyt bugeja, eikä käytettävyydessäkään ollut suurempia haasteita. Projektin koodi on kokonaisuudessaan järkevästi organisoitua ja laadukasta, vaikka hieman paranettavaa löytyykin. Hyvää työtä!

**Comment by satuso** [comment]
Kiitos palautteesta! Pidän nämä vinkit mielessä mahdollista jatkokehittelyä ja tulevaa varten 🙂
